# Generated by Django 5.2.14 on 2026-05-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_pin_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
