# Generated by Django 5.2.14 on 2026-06-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('learning', '0002_assignmentsubmission_grade_and_more'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('week', models.CharField(max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='class_videos/')),
                ('video_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academics.schoolclass')),
                ('session_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='results.sessionterm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academics.teacher')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
